src/dialogs/PreferencesDialog.cpp, src/dialogs/PreferencesDialog.hpp, src/dialogs/PreferencesPanel.cpp
Fixes #3.
When using MOVE_TO_NEXT_BLANK, MOVE_AFTER_LETTER must also be set, or
else the setting is ignored and the preference reset to unchecked when
the app is restarted.
Reverts commit 3670eff, which moved defines from hpp to cpp, because
PreferencesPanel.hpp depends on the value of
XWORD_PREFERENCES_LIVE_PREVIEW, which was undefined after this change.
We must define this variable somewhere accessible to both
PreferencesDialog.cpp and PreferencesPanel.hpp. This fixes live saving
of settings changes on OS X.
=> Fix grid control preference and OS X preference saving.

puz/Square.cpp
Fixes #17.
Many rebus solution grids don't actually have the rebus answers in
them, because the source format doesn't support them, or because the
puzzle creator doesn't know how to add them. When this happens, a
solver may enter the correct rebus solution, but it would be marked
wrong because the solution grid doesn't have the correct rebus answer.
So, if strict rebus checking is off, consider a rebus solution correct
if the solution has no rebus and the first letter of the user's
rebus solution matches the solution.
=> Make loose rebus checking more flexible.

src/XGridCtrl.cpp
Events should only be connected when a puzzle is open. All of the
event handlers assert that this is the case.
=> Fix crash introduced by 4d0e0d.

.gitignore
The current .gitignore ends up excluding folders like deps/luajit/lib
which should be included.
=> Only ignore build folders in the root.

src/App.cpp
For debug builds, if any Lua errors occur, we try to show the log file
when the app is closed. However, this is done by trying to execute the
file directly, which doesn't work on Mac/Linux. Instead, use a
cross-platform wxWidgets API to open the file in the default handler.
=> Use cross-platform API to show Lua errors.

src/premake4.lua
Otherwise, if the link already exists (e.g. for builds after the first
one), an extraneous link will be created at images/images and
scripts/scripts, because the existing symlink at the destination is
followed. This resolves the issue noted in the comments of issue #5.
=> Add -h when linking images/scripts folders.

scripts/download/sources.lua
pl.stringx.split's second argument isn't actually a regular
expression, despite its name. See:
https://github.com/stevedonovan/Penlight/blob/master/lua/pl/stringx.lua#L186
as plain is set to true if the re argument is provided. The "." at the
end of the folder name was being included in the file name causing the
read to fail.
=> Fix initial source load in download plugin.

src/dialogs/colorchoice.mm
Fixes #15.
Per the Apple developer documentation, systemFontOfSize is the font
used for standard interface items including menu items, so we should
use this size to ensure that our custom attribute labels (with colors)
are the same size as the default menu entry for "Other".
=> Fix font size inconsistency in Mac color choice selectors.

src/MyFrame.cpp
Fixes #11.
When a puzzle uses something other than "Across" and "Down", e.g. a
marching bands puzzle with "Bands" and "Rows", we would update the
pane captions but not the corresponding menu items in View -> Panes.
This causes a crash when MyAuiMgr attempts to look up the pane for the
stale menu item "Across" and fails to match it by caption with the
pane for "Bands".
So, whenever we update the clue lists, update the menu as well.
=> Fix crash in puzzles with alternate clue lists.

src/XGridCtrl.cpp, src/XGridCtrl.hpp, src/XGridRebus.cpp
Fixes #9.
-Make Escape work like Insert for rebus entry. Macs don't generally
have insert keys, which makes it more difficult to enter rebus entries
on them. Across Lite supports Escape on Mac, and there is no conflict
(except during grid selection mode, where Escape cancels out of the
grid, which still works as expected).
-Ensure keyboard focus returns to the grid once the rebus control is
closed.
-Make Escape work (as intended) to dismiss the rebus control. The
listener was in OnChar, but we never receive an OnChar event for
WXK_ESCAPE. Instead, add a listener for OnKeyDown and move the escape
key handling there, as XGridCtrl does.
=> Make rebus square entry easier on macOS.

src/MyStatusBar.cpp
Quick hack for issue #6, since right-aligning the timer is
non-trivial.
=> Move the timer slightly left to prevent truncation.

puz/Scrambler.cpp, puz/Scrambler.hpp, src/MyFrame.cpp
Fixes #19.
In some puzzles, multiple keys appear to result in a matching
checksum, but all but one will produce gibberish. Thus, as a rough
heuristic, we count the number of vowels in each unscrambled solution,
and unscramble using the solution with the most vowels.
Unfortunately, this means we must try every key instead of short-
circuiting when we find a valid one. Trying every key should only
takes a couple seconds, except that on Mac, UnscrambleDialog performs
quite slowly due to the frequent text updates. Speed up unscrambling
by limiting dialog updates to every 100th key.
=> Fix brute force unscrambling when multiple keys work.

src/dialogs/wxFB_Dialogs.cpp, src/dialogs/wxFB_Dialogs.fbp, src/dialogs/wxFB_Dialogs.h, src/dialogs/wxFB_MetadataFormat.cpp, src/dialogs/wxFB_MetadataFormat.fbp, src/dialogs/wxFB_MetadataFormat.h, src/dialogs/wxFB_PreferencesPanels.cpp, src/dialogs/wxFB_PreferencesPanels.fbp, src/dialogs/wxFB_PreferencesPanels.h, src/dialogs/wxFB_PreferencesPanelsOSX.cpp, src/dialogs/wxFB_PreferencesPanelsOSX.fbp, src/dialogs/wxFB_PreferencesPanelsOSX.h, src/dialogs/wxFB_TreePanels.cpp, src/dialogs/wxFB_TreePanels.fbp, src/dialogs/wxFB_TreePanels.h
Built using wxFormBuilder ToT from commit
b2b66a996ad28ff8efc6852eaa14918ee8dc7a1a. This resolves compiler
warnings due to deprecated wxFont usage.
=> Regenerate wxFormBuilder code.

scripts/download/init.lua, scripts/graph/dialog.lua, scripts/xword/pkgmgr/dialog.lua
While a modal dialog is open, menu and toolbar items are disabled.
This is undone when the dialog is dismissed. However, directly calling
Destroy() on the dialog skips resetting the state, which permanently
wedges the UI.
=> Properly close Lua plugin dialogs.

scripts/download/gui/download.fbp, scripts/download/gui/wxFB.lua, scripts/download/gui/wxFB.py, scripts/download/manager.lua, scripts/xworddebug/py2lua.lua, scripts/xworddebug/wxFB.fbp, scripts/xworddebug/wxFB.lua, scripts/xworddebug/wxFB.py
-Fix assert error with wxEXPAND|wxALIGN_CENTER_VERTICAL.
-Regegenerate wxFormBuilder and wxFB.lua files.
-Convert Windows to Linux line endings in py2lua.lua. Windows line
endings break the Lua interpreter on Mac (at least) with the newly
regenerated .lua files.
-Handle Window line endings when reading the last modified time from
the generated .lua files.
=> Lua plugin UI fixes.

src/App.cpp, src/paths.cpp, src/paths.hpp
Instead of working around the Windows-specific behavior of using the
parent directory of the .exe instead of the directory containing the
.exe itself when the .exe directory contains "debug", we can turn off
this behavior by calling DontIgnoreAppSubDir().
An alternative would be to force on portable mode for debug builds,
but this has other side effects which may not be desirable, e.g.
using a different config/settings from the release build.
Fixes #41
=> Clean up Windows hack in paths.cpp.

src/App.cpp, src/App.hpp
Since MyApp creates a new MyFrame object in OnInit, it should delete
that object in OnExit prior to deleting its ConfigManager instance.
Otherwise, MyFrame may still hold a registered callback in
ConfigManager, triggering a wxASSERT failure when ConfigManager's
destructor is called first.
Fixes #45
=> Fix crash on XWord close.

.travis.yml, README.md, appveyor.yml, build-wxwidgets.sh
This is a start towards resolving Issue #40. These configs build the
debug and release builds of XWord on Mac and Windows. If a new release
is created on GitHub, a release build will be zipped up and posted as
part of the release.
The --enable-unicode reference in README.md is removed, as this is the
default as of wxWidgets 2.9.
=> Configure Travis and AppVeyor builds.

scripts/download/gui/wxFB.lua, scripts/libs/md5.lua, scripts/xworddebug/py2lua.lua, scripts/xworddebug/wxFB.lua
Git doesn't save mtimes, so relying on mtime alone to determine
whether the input wxFB.py file has changed can lead to spurious
wxFB.lua regeneration. To mitigate this, store the md5sum of the input
file in the generated lua code as well, and check this in addition
when the mtimes indicate a possible change to the input.
If the md5sums are still identical, we touch the python file to put
things back in a reasonable state (so we don't have to calculate a
hash of the input file on every startup).
MD5 implementation via https://github.com/kikito/md5.lua
=> Make py2lua more robust in a git environment.

build-wxwidgets.sh
Some broken checks crept in but went undetected because the dependency
was available in the cache.
=> Fix the wxWidgets build script.

puz/formats/txt/load_txt.cpp
NumberGrid() can't be called before NumberClues(), as NumberGrid()
calls GenerateWords() which expects the clues to have been numbered.
There is also an extraneous call to GenerateWords() which can be
removed.
=> Fix parsing of TXT format puzzles.

README.md, build-wxwidgets.sh, wxwidgets-smooth-scroll-modals.patch
This appears to be a bug in wxWidgets
(http://trac.wxwidgets.org/ticket/17737). The patch has been discussed
with the wxWidgets maintainers who are open to it with further
testing. It appears to resolve the issue with all of the modal dialogs
in XWord without introducing noticable regressions.
In the future, we should be able to remove this upon upgrading to the
next release of wxWidgets which includes this fix (if/when accepted).
Note that the build caches in Travis/Appveyor must be manually cleared
before this change is merged, as otherwise the cached, compiled
version of wxWidgets from prior builds will be used.
Fixes #27
=> Fix two-finger scrolling in modals on Mac.

.travis.yml
Newer OS X versions require either wxWidgets 3.1.1 (which is
backwards-incompatible and will involve more app changes) or patches
to 3.1.0 in order to compile. Either will be more involved, so just
get builds working again first.
See #58
=> Pin to previous OS X image to fix Mac builds.

.gitignore, appveyor.yml, dist/XWord.nsi, doc/link_check.py, doc/make_help.bat, doc/make_help.cmd, doc/markdown.py
- Fix doc/ python scripts to work on Python 3
- Remove launch step from doc/make_help.bat
- Work around HTML Help Compiler succeeding with code 1
- Use relative paths in dist/XWord.nsi
- Update file list in dist/XWord.nsi
- Add .gitignore for doc + dist outputs
- Add AppVeyor config to run doc + dist steps
=> Build XWord installer for Windows (#40).

build-wxwidgets.sh, premake4.lua, puz/parse/pugixml/pugiconfig.hpp, puz/parse/pugixml/pugixml.cpp, puz/parse/pugixml/pugixml.hpp
Xcode 10 removes support for libstdc++. Use libc++ instead, which
should also work on OS X 10.7+ (the current minimum version).
Update wxWidgets build script. Update pugixml to the latest version to
fix compilation errors when using libc++.
=> Fix builds with Xcode 10+.

.travis.yml
Previous names didn't actually exist, so both configurations were actually using the default debug configuration.
=> Fix configuration names in Travis config.

.travis.yml, appveyor.yml, build-wxwidgets.sh
Avoids reusing a cached wxWidgets build whenever the version changes. In
the future, if we add patches to the wxWidgets build, or otherwise
change how we build it, we can add another identifier to the directory
to identify the configuration and invalidate old caches.
=> Add wxWidgets version to the build directory.

src/xwordlua.cpp
Normally the luapuz library would be loaded by lua_openxword prior to
any use of Lua. However, on Mac (at least), the library would fail to
load because it would be loaded prior to the package path being set.
This was fine as long as the debug plugin was enabled, since the debug
plugin also loads luapuz and is initialized after the package path is
set. However, with the plugin disabled, nothing loads luapuz, and we
fail to push a Puzzle onto the Lua stack.
Swap the loading order to ensure that luapuz loads successfully, even
if the debug plugin is disabled. Also log a warning when the loading
fails to make future issues clearer. Note that we can't use
LogLuaMessage here without further tweaks because plugins are loaded
on a background thread, and setting the message count can't be done on …
=> Fix crash when opening a puzzle with debug plugin disabled.

puz/Puzzle.hpp
When Puzzle.GetMeta was called for a key which didn't exist, it would
write an entry with an empty key and value into the metadata table. JPZ
serialization would convert this into an "<:anonymous />" XML tag which
is invalid in the JPZ specification and which breaks the Crossword Nexus
parser. By skipping this modification and leaving the metadata table
untouched, we prevent this invalid tag from being written.
See discussion in #66
=> Fix metadata corruption when saving JPZ files.

src/widgets/HtmlText.cpp, src/widgets/HtmlText.hpp
On a Windows device with a high-density display, it was taking
hundreds of milliseconds to update from one clue to another. Rather
than run a linear search for the optimal font size, we can do a binary
search instead, ensuring we only need
log(maxFontSize-minFontSize)/log(2) layout passes.
We can also avoid any work if the clue text hasn't changed, e.g. if
we're navigating within the same word. This helps reduce unnecessary
flicker.
See #82
=> Improve clue prompt rendering performance.

scripts/xword/init.lua
curl_global_init is not thread-safe - not only is it not supposed to
be called in more than one thread at the same time, but since it
itself makes calls to thread-unsafe APIs (e.g. in SSL libraries) that
may also be used outside of curl, it's technically not safe to be
doing *anything* on any other thread at the same time.
However, lua initialization starts up various background tasks using
the task API, which spawns new threads for each task, and those tasks
depend on curl. For example, the package manager is started to check
for updates. Curl is also loaded on the main thread in parallel.
To mitigate this problem, we can explicitly require luacurl (and thus
call curl_global_init) prior to loading the task library (and thus
starting background thrads which might call curl_global_init). …
=> Mitigate race condition in curl initialization.

scripts/download/gui/popup.lua, scripts/download/gui/puzzle_grid.lua
Fixes crash when using Show/HideWithEffect and keeps focus on the
downloader window even when a popup is being shown.
Fixes #54
=> Make Downloader more stable on Mac.

puz/formats/jpz/save_jpz.cpp, puz/parse/xml.cpp, puz/parse/xml.hpp
This offers a bit more flexibility to support JPZ files with clues that
are only partially formatted, e.g. "<i>italicized part</i> unformatted
part". While the spec suggests that mixed content is "not supported",
and indeed Puzzle Solver can't handle such content, the online solver at
Crossword Nexus does handle it, and without such support, we'd lose the
ability to have italicized titles in clues when importing .rgz files.
See #86
=> Fix writing of mixed content in JPZ clues.

src/MyFrame.cpp
For some reason, on Windows with wxWidgets 3.1.3, a window at the left
edge of the screen has a small negative left coordinate instead of 0
as expected. Rather than snap negative positions to 20 pixels, we
allow slightly negative positions without repositioning them on the
next startup. We still reposition windows that are significantly
offscreen in case this was unintentional or the saved position was
invalid.
Fixes #84
=> Fix initial window positioning on Windows.

build-wxwidgets.sh
These libraries are not built into OS X by default, so you'd need to
install them via homebrew first, and there may be version
inconsistencies. This makes the OS X binary easier to distribute.
=> Use wxWidgets' built-in libpng/jpeg/tiff on Mac.

src/dialogs/TreePanels.hpp
Since these can be scripts, we don't want fancy quotes to be
automatically substituted.
This bug also impacts some of the xworddebug lua plugin UI, but this
would be harder to fix since the generated bindings don't include
WXOSX-specific methods, and this is less impactful since it's debug
only.
See #70
=> Disable smart quotes in metadata settings text boxes.

scripts/import/newsday.lua
Previously, the script called NumberGrid() before NumberClues(). This is
broken because NumberGrid() will call GenerateWords() to generate words
for each clue; however, at this point, the clues are numbered
incorrectly (sequentially) because NumberClues hasn't been called yet.
Fix this by first generating the correct clue numbers before numbering
the grid and generating the clue words.
uClick XML import has the same order, but is not impacted because uClick
XML already includes the clue numbers for each clue.
=> Fix Newsday .txt import word generation.

src/dialogs/PreferencesDialog.cpp
Since the dialog is kept as a singleton, we need to reload the old
settings snapshot each time the dialog is shown, so that we can restore
settings from that snapshot if the user makes changes and then elects to
cancel them.
Fixes the issue discovered in the discussion in #64.
=> Reload old settings when showing pref dialog.

.travis.yml, appveyor.yml, dist/packages_template.lua, scripts/xword/pkgmgr/updater/init.lua
- Generate packages_windows.lua and packages_mac.lua as part of release
builds and include them in the release artifacts. For now, since we are
only distributing plugins inside the distribution, we can use a simple
template and a sed-based find/replace to generate these files.
dist/gen_packages.lua works for this purpose as well, but requires Lua
to be installed in the CI environment, which is non-trivial. We can
always revisit if we decide to distribute plugin packages separately.
- Point the auto-updater to a known location on GitHub pages to search
for new packages.
With this along with #102 and #103 (along with #106 for Windows), the
full distribution workflow is functional on Windows/Mac. Pushing a new
build consists of the following steps:
1) Create a GitHub release. Set the tag to …
=> Complete configuration for auto updater.

scripts/download/gui/config_gui.lua, scripts/download/gui/wxFB.lua, scripts/libs/wx/lib/mixins/listctrl.lua, scripts/xword/pkgmgr/dialog.lua, scripts/xworddebug/py2lua.lua, scripts/xworddebug/wxFB.lua, src/MyFrame.cpp, src/MyStatusBar.cpp, src/dialogs/TreeCtrls.hpp, src/dialogs/TreePanels.hpp, src/dialogs/fontpicker.hpp, src/dialogs/wxFB_PreferencesPanels.cpp, src/dialogs/wxFB_PreferencesPanels.fbp, src/dialogs/wxFB_PreferencesPanels.h, src/dialogs/wxFB_PreferencesPanelsOSX.cpp, src/dialogs/wxFB_PreferencesPanelsOSX.fbp, src/dialogs/wxFB_PreferencesPanelsOSX.h, src/dialogs/wxFB_TreePanels.cpp, src/dialogs/wxFB_TreePanels.fbp, src/dialogs/wxFB_TreePanels.h, src/premake4.lua, src/utils/ConfigManager.hpp, src/utils/ToolManager.cpp, src/widgets/ScaledSpinCtrl.h
The primary functional change here is that in the premake config, we
declare that the app is DPI aware, which turns off compatibility
rendering and allows the app to draw pixel-perfect UI on high-density
displays.
However, in any place that we currently specify a size in pixel units,
we must first scale the size to density-independent pixels to ensure
that UI elements are the same actual size regardless of the density.
While wxWidgets occasionally handles this automatically, in some
cases we must do the scaling ourselves. This commit handles most visible
places in the UI.
Specific notes:
- wxFormBuilder doesn't support hidpi yet. For Lua script UIs (generated
w/ py2lua), wrap any use of wxSize in a FromDIP call to scale it. For
C++ UIs, the only noticeable problem is with wxSpinCtrl; …
=> Make XWord hidpi-aware.

lua/luapuz/bind/luapuz_puz.cpp, lua/luapuz/bind/luapuz_puz_Grid.cpp, lua/luapuz/bind/luapuz_puz_Square.cpp, lua/luapuz/bind/puz_defs.lua, puz/Grid.cpp, puz/Grid.hpp, puz/Puzzle.cpp, puz/Square.cpp, puz/Square.hpp, puz/formats/jpz/load_jpz.cpp, puz/formats/jpz/save_jpz.cpp, src/MyFrame.cpp, src/XGridCtrl.cpp, src/XGridCtrl.hpp, src/XGridDrawer.cpp
This is a new extension to JPZ files being used by Outside the Box
puzzles and supported by the Crossword Nexus solver. It mostly follows
the JPZ standard, but uses the `<acrostic>` root XML tag instead of
`<crossword>` and requires that entries be propagated to their partner
squares with the same number.
This commit adds support for the new "Acrostic" grid type, enabling
loads/saves from the JPZ format. "clue" type squares are now supported -
these are used for the letters of each clue as well as punctuation in
the quote. Changes made to square contents (letters/flags) are
propagated to partner squares. The top-right text is changed to align
precisely with the clue number, as it was a pixel off before.
The primary remaining pieces for parity with Crossword Nexus are:
1.  Fixed …
=> Initial work on Acrostic support.

src/MyFrame.cpp
The icon was only set to yellow for the "Notes" field, but notes may be
shown for other metadata like JPZ descriptions according to the
IsNotes() helper function. Use the same function to determine whether to
show the notes_new icon so that these two are consistent.
=> Show yellow notes icon for notes-like metadata.

src/MyFrame.cpp, src/html/parse.hpp
Puzzle metadata, including titles, can include HTML, which isn't
supported by the window title bar. So we parse the title as HTML,
ignoring all style tags and just combining the text into a flat
string, before setting the title.
Resolves `&amp;` showing up in the title rather than `&`.
See #117
=> Clean up HTML when setting window title.

src/MyFrame.cpp
Most of the time is spent yielding, so yield every 100 keys instead of
every key attempted. This is for debugging anyway, so high UI
responsivity isn't particularly critical.
=> Speed up brute force unscramble on Windows.

puz/formats/jpz/load_jpz.cpp
Ensures that leading/trailing whitespace is removed when reading
XML elements.
See #117
=> Trim text and inner XML when parsing XML.

src/MyFrame.cpp
MyFrame::LoadPuzzle uses wx2file to convert wxString filenames to
std::string filenames suitable for use with native C++ APIs, but
MyFrame::DoSavePuzzle was using puz::encode_utf8(wx2puz(...)) which
appears to mangle accents on Windows. Use wx2file everywhere.
Also make line endings consistent so VS stops complaining.
Fixes #133
=> Use the same filename conversion when loading and saving files.

src/MyFrame.cpp, src/XGridCtrl.cpp
Previously, we focused on the first white square and an arbitrary word
in the Across direction containing that square.
Now, if there is either exactly one clue list, or a clue list labeled
"Across", we focus on the first square of the first word in that list.
Otherwise, we fall back to the same logic as before.
See #134
=> Refine selection of initial square.

lua/luapuz/bind/luapuz_puz.cpp, lua/luapuz/bind/luapuz_puz_Grid.cpp, lua/luapuz/bind/puz_defs.lua, puz/Grid.cpp, puz/Grid.hpp, puz/Square.cpp, puz/Square.hpp, puz/formats/jpz/load_jpz.cpp, src/XGridCtrl.cpp
Coded crosswords have no clues; instead, each square is numbered from
1-26, and each number represents a particular letter to be determined.
All squares with the same number contain the same letter.
Supporting these puzzles is quite similar to Acrostics in that we can
consider all the squares with the same number to be "partners" and
propagate changes to one square to all partner squares. We extend the
partner concept to support multiple partner squares instead of just one.
This provides a functional interface, but there are some drawbacks:
-  The cluelists still appear (Across/Down) despite being empty.
Crossword Solver hides the unnecessary cluelist for this puzzle type.
-  The rendering performance is quite slow, probably because there are
so many partner squares to update each time …
=> Add support for coded crosswords (aka "codewords").

src/XGridCtrl.cpp
Avoids a call to GetDirection() which crashes. We'll just assume the
first direction is ACROSS for these puzzles.
Fixes #138
=> Skip inference of "first" clue list on Diagramless puzzles.

puz/Checksummer.cpp, puz/Puzzle.cpp, puz/Puzzle.hpp, puz/formats/puz/save_puz.cpp, puz/puzstring.cpp, puz/puzstring.hpp, src/MyFrame.cpp
Previously, extra metadata outside the standard PUZ notes field was
stored in a proprietary META section that is unknown to other
applications. This would result in an inconsistent experience, where a
JPZ file with visible notes from a non-standard field would be saved as
a PUZ that would then lose visible notes when viewed in Across Lite.
With this change, we remove support for the extra META section. Instead,
when saving to PUZ, we concatenate all metadata fields which are
considered to be notes (using section headers and separators) and insert
them as plaintext into the PUZ notes field. Of course this is not a
perfect rendering, but in the most common case of having one field for
notes but which might not be the <instructions> field as XWord expects,
this does a reasonable job.
There …
=> Propagate puzzle notes to PUZ files in the notepad.

puz/Clue.cpp, puz/Clue.hpp, puz/Puzzle.cpp, src/XGridCtrl.cpp
Change Clues from a map, which is ordered alphabetically, to a vector,
which retains insertion order. This should make no difference for
regular crosswords (and there is special logic to handle Across/Down
even if out of order), but retains the order from variety puzzle formats
which is more likely to be the intended viewing order.
Also expand the logic used to select the initial clue; previously, we
only selected the first clue's first square if there was one clue list.
We now do this even if there is more than one clue list. This is more
likely to be reasonable now that clue list ordering is maintained from
the original file.
Fixes #134
=> Respect clue list ordering from file and expand initial clue selection.

puz/formats/jpz/load_jpz.cpp, puz/formats/jpz/save_jpz.cpp
@jpd236 any idea if this is legit for the jpz format? It's just copied from the white square section below, so it's a valid `<cell>` attribute, just not sure if it breaks crossword solver. Edit: it does work in the crosswordnexus solver at least, so that's a good sign.
=> Support black square color in jpz

src/XGridCtrl.cpp
We can only focus on squares which are white (unless the puzzle is
diagramless). So when a user presses an arrow key, even if the next
square in that direction is part of the current word, we should not
attempt to focus on it unless one of those conditions match.
Fixes #146
=> Prevent focusing on black squares within a word.

puz/Clue.hpp, puz/puzstring.cpp, puz/puzstring.hpp
When setting a ClueList, normalize them to the canonical "Across" and
"Down" as is used elsewhere in XWord. This fixes features like reuse of
existing settings for the Across and Down clue panes and saving the file
as an Across Lite .puz file.
Note that this results in the displayed clue list using the canonical
name and not the provided name, since MyFrame::ShowClues is built around
using the keys and not the titles. However, this is only a minor
cosmetic difference that seems harder to fix.
See #140
=> Improve handling of different capitalizations of "Across" and "Down".

src/XGridDrawer.cpp
Use the same background rendering behavior as for regular white squares
instead of rendering as a black square, and don't render borders. This
matches the Crossword Nexus behavior.
=> Improve rendering of annotation squares.

src/MetadataCtrl.cpp
@jpd236 see if this fixes #117 for good. This should work for all formats, not just jpz, if you happen to have a specially crafted puz around.
=> Fix metadata formatting issues w/ quotes

src/XGridCtrl.cpp
Adjust all default usage of FindPrevSquare and FindNextSquare to use
the FIND_WHITE_SQUARE find function to ensure they skip over any
annotation squares instead of trying to focus on them.
See #146
=> Fix more issues with navigating through grids with annotation squares.

puz/Checksummer.cpp, puz/Checksummer.hpp, puz/formats/puz/load_puz.cpp, puz/formats/puz/save_puz.cpp, puz/puzstring.cpp, puz/puzstring.hpp
When reading a .puz, if the version code is 2.x (instead of 1.x), we
decode strings as UTF-8 instead of Windows-1252. This includes metadata
and clues, but not the grid itself.
When saving a .puz, if any metadata or clues uses characters which
cannot be encoded in Windows-1252, we save as a 2.x file and encode the
strings as UTF-8. This keeps backwards compatibility as wide as
possible, since not all .puz readers can handle 2.x files.
Loading/saving has been tested successfully with a basic UTF-8
character as used in the WaPo puzzle on 2021-06-20; the re-saved file
can still be loaded in Across Lite and has correctly-encoded text.
However, while the more complex example .puz with emoji clues can be
loaded, saved, and successfully loaded in Across Lite, the clues are
corrupted in the …
=> Initial support for reading and writing UTF-8 .puz files.

src/XGridCtrl.cpp
The intent is to navigate to the next square in a different word that
*could* be part of a word, even if it isn't. This is intended to be a
superset of all possible words, but can actually be stricter - for
example, if there is a three letter word with an annotation square in
the middle, neither of the two outer squares are considered potential
words because a word must have at least two letters.
So, in addition to accepting potential word candidates, we also accept
actual words, since some file formats support specifying words
explicitly rather than calculating them via this algorithm for potential
words.
See #146
=> Fix shift-arrow navigation with annotation squares.

puz/puzstring.cpp
Windows uses 2-byte wchars and UTF-16, so emojis and other characters
which require more than 2 bytes were being encoded/decoded incorrectly
by trying to fit them into one wchar. Migrate to pugixml's UTF8<->wchar
conversion methods which work on all platforms.
Fixes #137
=> Fix unicode issues on Windows.

src/html/parse.cpp
The control itself draws the background. The _HTML_ background is per
cell, and a solid color background (even white) can potentially draw on
top of neighbor cells. This can appear, e.g. with the rightmost
character of italic text getting cut off.
Fixes #158
=> Use transparent background in HTML windows

src/XGridCtrl.cpp
In the old logic, we only moved to the start of a word explicitly when
the arrow direction and focused direction were different:
https://github.com/mrichards42/xword/blob/cd5d08cf9cd053025a6baa92ad13b818b1e3f7c8/src/XGridCtrl.cpp#L1674
The new logic applied this unconditionally. In most cases, this seems to
have the same behavior, in that if the word being moved to has any blank
squares, we move to the first blank in the word anyway. But if the word
being moved to is full, we should stay in line with the current focused
square to avoid jumping around the grid. This makes it easier to
navigate through a filled section of the grid.
Fixes #160
=> Fix regression in shift-arrow behavior on filled words.

puz/puzstring.cpp
As pointed out in #156, this returns false incorrectly for the Unicode
characters which are in the 128-160 range of the Cp1252 charset. This
means that XWord will unnecessarily use the less-supported 2.0 version
when saving .puz files if one of these characters are used.
=> Fix bug in can_encode_puz.

puz/formats/ipuz/load_ipuz.cpp
v2 is generally a safe expansion on top of v1 - ipuz.org notes that some
fields have been deprecated, though the only explicit mention of
"deprecated" on the v2 doc relates to a field in Sudoku puzzles. There
may be some additional features that aren't yet supported, but these can
always be added later.
See #172
=> Remove version check from ipuz reader.

puz/Square.cpp
=> Stop at barred squares when finding word boundaries.

puz/formats/jpz/save_jpz.cpp
See https://crossword.info/xml/crossword-compiler-applet.xsd which
contains the correct values.
=> Fix namespace when saving JPZ files.

puz/formats/ipuz/load_ipuz.cpp
iPuz supports two types of color declarations. Hex colors are
straightforward and fully supported. Puzzles can also use arbitrary
integers, which are app-defined values. For example, and app can define
0 = Black, 1 = Blue, 2 = Red, etc. This method seems less likely to be
used in practice, and it is non-trivial to define a palette that would
work well for arbitrary puzzles and user preferences. So for simplicity,
we treat 0 as Black per the spec recommendation, and everything else as
equivalent to "highlighted" (shaded gray).
Fixes #186
=> Support cell background colors in iPuz files.

puz/Checksummer.cpp, puz/formats/puz/load_puz.cpp, scripts/import/rowsgarden.lua
XWord assumes that metadata and clue strings are valid XML/HTML when
rendering. This works fine for JPZ since the input is itself a valid XML
file, but may not be the case for other formats.
The clues and notepad were already being escaped when reading PUZ files
(and unescaped when writing them); we should do the same for the title,
author, and notes. Similarly, when reading RGZ files, we should escape
XML for any free-form text.
See #182
=> Ensure XML characters are escaped when reading PUZ/RGZ.

lua/luapuz/bind/luapuz_puz.cpp, lua/luapuz/bind/luapuz_puz_Puzzle.cpp, lua/luapuz/bind/puz_defs.lua, lua/luapuz/bind/puz_overrides.lua, puz/Clue.cpp, puz/Clue.hpp, puz/Puzzle.hpp, puz/formats/ipuz/load_ipuz.cpp, puz/formats/jpz/load_jpz.cpp, puz/formats/puz/load_puz.cpp, scripts/import/amuselabs.lua, scripts/import/rowsgarden.lua
Previously, this was done on an ad-hoc basis in certain formats/fields,
but not all, which could lead to inconsistent/incorrect handling of
special characters like & and <.
Now, all metadata fields and clues default to assuming that the provided
strings are plaintext and escape XML characters so that XWord (which
renders them as HTML) renders them correctly. Functions take an
additional, optional is_html bool parameter which can be set to true if
the input should be left unchanged (since it is already valid HTML).
This is used for JPZ, IPUZ, Amuse Labs imports, and Rows Garden clues
(where we convert * to italic tags, and escape the rest of the clue
manually).
Fixes #182
=> Escape XML by default in metadata and clue text.

scripts/nextblank/init.lua
nextblank logic needs to skip void cells, since it is impossible to set
focus on such cells. So we only include "white" cells (where user input
is possible).
Fixes #190
=> Fix crash in nextblank with void cells.

puz/Square.cpp
- Permit "*" as a valid grid character. While Across Lite doesn't
support it, other formats do. It can't be entered directly (since it is
bound as the shortcut for circling/uncircling a letter to match Across
Lite), but it can be entered as a rebus.
- When setting square text or solutions, never set the empty string,
even if ToGrid returns one (due to an invalid character, namely a black
square (".") or the symbol indicator ("[")). This ensures that bounds
checks pass in HasSolutionRebus.
See #185
=> More flexible solution character handling.

premake4_wxlibs.lua
There is an accidental % symbol in the match function.
=> Fix typo in wxWidgets folder version matching

src/XGridDrawer.cpp
This failed when printing a blank grid (which sets neither DRAW_USER_TEXT nor DRAW_SOLUTION flags).
Bug reported in an email this morning.
@jpd236 since I haven't done much (anything?) with annotation squares, mind giving this a quick peek to see I missed anything obvious? I think this is a pretty simple fix, but you never know.
=> Always draw annotation square text

src/MyFrame.cpp
While AUI is mysterious, what appeared to be happening is that the panels were added in two separate update phases: first the grid, clue prompt, and notes as part of MyFrame::ManageWindows, and then the clue list panels later on as part of MyFrame::ShowClues. While the clue panel's best width property does get restored from the prior config when it is created in this second phase, AUI does not seem to respect it, capping it at a maximum value. I'd speculate this is because the grid has expanded to take the space that would have been occupied by the clue panel, and would thus need its sized reduced in tandem with adding the clue panels back to the layout.
In any case, forcing a call to ShowClues as part of ManageWindows adds the clue panels a bit earlier on, which appears to be enough to …
=> Retain clue list panel width across restarts.

src/XGridCtrl.cpp, src/XGridDrawer.cpp, src/XGridDrawer.hpp
Previously, focused or selected cells would be colored with the appropriate color regardless of the cell background, which causes shaded cells to lose their contrast against other cells in the puzzle. This can interfere with solving, as it is important to be able to tell which cells are shaded in a focused word.
We adopt an approach from crosswordnexus/html5-crossword-solver#91: if a focused or selected cell has a non-white background, we blend the background color with the focus/selection color to determine the cell color. We darken the background color when blending to ensure sufficient contrast.
This should resolve much of #178. Cell background images will still be hidden when focused/selected; these are significantly rarer and harder to handle.
=> Blend square background color with focus/selection colors.

puz/formats/ipuz/load_ipuz.cpp, puz/formats/jpz/load_jpz.cpp, puz/formats/jpz/save_jpz.cpp, src/XGridCtrl.cpp
- Support IPUZ/JPZ files without solutions, leveraging the existing PUZ grid flag. For IPUZ files, we can look at whether the solution grid is present. For JPZ files, we look at whether any letter squares have non-empty solutions.
- Respect the "no solution" grid flag when evaluating the completion status. This prevents us from thinking that the grid is correctly filled when it is fully empty.
=> Improve handling of puzzles without solutions.

puz/formats/ipuz/load_ipuz.cpp
We treat these identically to jpz files with hint="true" and prefill the user's solution with the square's solution.
Fixes #213
=> Support square with a value in ipuz.

appveyor.yml
Available versions taken from:
https://www.appveyor.com/docs/macos-images-software/
Xcode 14.2 (the current default) requires setting
MACOSX_DEPLOYMENT_TARGET to 10.13 or higher; XWord currently uses 10.10. Eventually we will need to raise the minimum (and drop support for 10.10-10.12), but this should keep things working for the time being.
=> Fix Mac builds by pinning to an older Xcode version.

src/MyFrame.cpp, src/html/parse.hpp
This is a native message ctrl that can't contain html tags, so strip them out like we do titles.
=> Strip html tags from completion dialog
